import { Manrope, Playfair_Display } from "next/font/google";
import "./globals.css";
import NavbarContext from "@/context/NavbarContext";
import LenisWrapper from "@/components/LenisWrapper";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

export const metadata = {
  title: "Velora - Real Estate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisWrapper>
          <NavbarContext>
            {children}
          </NavbarContext>
        </LenisWrapper>
      </body>
    </html>
  );
}
